export const FETCH_STORES = 'FETCH_STORES'
export const FETCH_ITEMS = 'FETCH_ITEMS'
export const ADD_ITEM = 'ADD_ITEM'
export const UPDATE_ITEM = 'UPDATE_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const FETCH_ERROR = 'FETCH_ERROR'
